### ISSUE TITLE
Code Release

### ISSUE THREAD

**Issue by ErisRolo** [tobias-kirschstein/gghead#1]
Nice work! When do you plan to release the code?

**Comment by tobias-kirschstein** [comment]
Hi,

Thanks for your interest in our work.
We will release the code for reproducing our experiments in a few weeks time. Please stay tuned!

**Comment by NothingL** [comment]
any updates on this?

**Comment by tobias-kirschstein** [comment]
We are working on it. Expect to release something in around 2 weeks time

**Comment by tobias-kirschstein** [comment]
We released the inference code now. Training should follow shortly

**Comment by ErisRolo** [comment]
Hi! I saw your experimental results on the AFHQ dataset. Could you please explain how to replace the background in cat face images? I have tried MODNet, but it doesn’t work well on some images.

**Comment by tobias-kirschstein** [comment]
We have released the training code now as well. Please check it out!

> Could you please explain how to replace the background in cat face images? I have tried MODNet, but it doesn’t work well on some images.
Yes, MODNet is not perfect but we still used it for AFHQ. Even with some failed segmentations the GAN training still succeeded.
We have also released our computed background masks now
