### ISSUE TITLE
Extraction of UV color in png 

### ISSUE THREAD

**Issue by 99csg** [tobias-kirschstein/gghead#15]
![화면 캡처 2024-11-30 164249](https://github.com/user-attachments/assets/222fd524-b393-46ad-9181-89c9d85fbeea)

Great Work !!
I want to know how to extract uv color in png file like in your paper 
I tried in sample_heads.py and add code line like below but it's output is not plausible, is idx from 9 to 11 is right? 

                output = G.synthesis(w_batch, c_batch, sh_ref_cam=sh_ref_cam, return_masks=True, 
                                     noise_mode='const', return_uv_map=True,
                                     neural_rendering_resolution=resolution)

                **image_tensor = output.gaussian_attribute_output.uv_map[0,9:12,:,:] # 8 22 256 256**

                image_tensor = (image_tensor - image_tensor.min()) / (image_tensor.max() - image_tensor.min()) * 255
                image_tensor = image_tensor.byte()

                image = Image.fromarray(image_tensor.permute(1, 2, 0).cpu().numpy())
                image.save("/hdd1/csg/src/gghead/debug/rgb_output.png")

**Comment by tobias-kirschstein** [comment]
Thanks!
The version released in this repository is slightly more complicated wrt colors since it is using a spherical harmonics degree of 1 to model view dependent effects.
Hence, it is actually 12 channels that are responsible for color, not just 3.
Here is a snippet that should get you going:

```
from gaussian_splatting.utils.sh_utils import eval_sh
from gaussian_splatting.scene.cameras import pose_to_rendercam

# Obtain color map
color_map = output.gaussian_attribute_output.uv_map[0, 9:21]  # [SH, H, W]
color_map = model._apply_color_activation(color_map)

# Obtain position map
position_map = output.gaussian_attribute_output.uv_map[0, :3]  # [3, H, W]
position_map = model._apply_position_activation(position_map)
mesh_position_map = position_map

# Evaluate spherical harmonics from a frontal viewpoint to get RGB
H = 256
W = 256
gaussian_sh_ref_cam = pose_to_rendercam(pose_front, DEFAULT_INTRINSICS, 512, 512, device=device)
color_map = color_map.permute(1, 2, 0).view(H, W, -1, 3)

sh_degree = model._config.gaussian_attribute_config.sh_degree
shs_view = color_map.transpose(2, 3).view(H, W, 3, (sh_degree + 1) ** 2)

dir_pp = (mesh_position_map.permute(1, 2, 0) - gaussian_sh_ref_cam.camera_center.repeat(1, 1))
dir_pp_normalized = dir_pp / dir_pp.norm(dim=-1, keepdim=True)
sh2rgb = eval_sh(sh_degree, shs_view, dir_pp_normalized)
color_map = torch.clamp_min(sh2rgb + 0.5, 0.0)

plt.imshow(color_map.cpu().numpy())
```

For the example in the `inference.ipynb` it should plot something like this:

![image](https://github.com/user-attachments/assets/0dffb7bc-4fe0-4d19-9b8a-b214091bea49)

**Comment by 99csg** [comment]
thanks a lot!
