### ISSUE TITLE
Looking forward for your releasing codes

### ISSUE THREAD

**Issue by VincentHu19** [tobias-kirschstein/gghead#2]
good work! Looking forward for your releasing codes!

**Comment by tobias-kirschstein** [comment]
We released the inference code now. Training should follow shortly

**Comment by VincentHu19** [comment]
> We released the inference code now. Training should follow shortly
Thanks for your reminding! Looking forward for future updates 😊

**Comment by tobias-kirschstein** [comment]
We have also released the training code now. Please check it out!
