### ISSUE TITLE
Rendered image is almost black

### ISSUE THREAD

**Issue by zzb2001** [tobias-kirschstein/gghead#3]
![39855ac9-e8b8-4197-82d4-9b9f915f450d](https://github.com/user-attachments/assets/9aa94c4f-d4e7-4d74-86fc-949132236258)
![55bd9d03-643b-4599-b52c-38aa4f846804](https://github.com/user-attachments/assets/1ef96631-3345-4451-84ba-9baa8505bedf)
Hey Tobias, amazing work! 🎉 I’ve been diving into your rendering code and I'm really impressed with the depth and detail of your approach. Kudos to you for such a solid contribution!

Quick question though—I tried running the rendering script, and while everything runs smoothly, the output I get is nearly all black. The image is in RGB format, but it looks like my scene is trapped in eternal night! 🌑🖼️ Any idea what might be causing this? I’m sure it’s something small that I’m missing.

Looking forward to your insights! 😊

**Comment by tobias-kirschstein** [comment]
Hi thanks for your interest in our work.

I never had such outputs. I tested the rendering code on multiple machines and it works fine there.
What exactly are you trying? Just running
```python scripts/render_interpolation.py GGHEAD-1```?

**Comment by tobias-kirschstein** [comment]
How does it look like in the visualizer? Is it also black there?

**Comment by tobias-kirschstein** [comment]
Closing this issue as it seems like no further help is needed.
@zzb2001 if you found out what the issue was, it would be great if you could let us know!
