### ISSUE TITLE
How does Teeth/Glasses/Hair/Clothing Work ?

### ISSUE THREAD

**Issue by Ryan-Vereque** [tobias-kirschstein/gghead#8]
I would like to confirm if ability to learn teeth/glasses/hair/clothing are merely the result of the model learning to transform some of the template mesh (presumably in a related area) into what look like teeth/etc, or something else is going on ?

**Comment by tobias-kirschstein** [comment]
Hi, yes the template mesh is only there to have some initialization and reasonable shape for regularizing the Gaussians' positions but other than that the model is completely free to use the Gaussians to model whatever part of the face it likes. So, for example, a Gaussian rigged to an eye vertex may not always only model the eye
